export const ADD_UNIT = 'ADD_UNIT'
export const READ_ALL_UNITS = 'READ_ALL_UNITS'
export const REMOVE_UNIT = 'REMOVE_UNIT'
export const UPDATE_UNIT = 'UPDATE_UNIT'
export const SHOW_LOADER = 'SHOW_LOADER'